server:
  port: 8080

spring:
  application:
    name: sda-serwery
  datasource:
#    jndi-name: java:/comp/env/jdbc/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.3:3306/demo?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root

#logging:
#  file: ../logs/sda-serwery.log
#  level:
#    root: INFO
#    io.mbab.sda: DEBUG